---

- name: pull release from github
  get_url:
    url: https://github.com/csirtgadgets/bearded-avenger/archive/{{ cif_release }}.tar.gz
    dest: /tmp/bearded-avenger-{{ cif_release }}.tar.gz
  when: GH_TOKEN == ""
  tags: test

# github likes to throttle when
- name: pull release from github
  get_url:
    url: https://github.com/csirtgadgets/bearded-avenger/archive/{{ cif_release }}.tar.gz
    dest: /tmp/bearded-avenger-{{ cif_release }}.tar.gz
    headers: "Authorization: Token {{ GH_TOKEN }}"
  when: GH_TOKEN is defined and GH_TOKEN != ""
  tags: test

- name: unarchive
  unarchive: src=/tmp/bearded-avenger-{{ cif_release }}.tar.gz dest=/tmp/

- name: install requirements
  command: pip install -r dev_requirements.txt chdir=/tmp/bearded-avenger-{{ cif_release }}

- name: run tests
  command: python setup.py test chdir=/tmp/bearded-avenger-{{ cif_release }}

- name: install cif
  command: python setup.py install chdir=/tmp/bearded-avenger-{{ cif_release }}