---
- user: name="{{ app_user }}" shell=/bin/bash append=yes

- name: Ensure path has correct permissions
  file: path={{ app_user_home }} owner={{ app_user }} group={{ app_user }} mode=0750

- user: name="{{ ansible_env.SUDO_USER }}" groups={{ app_user }} append=yes

- name: Ensure app user has a .profile
  file: path="{{ app_user_home }}/.profile" state=touch owner={{ app_user }} group={{ app_user }} mode=0660

- name: Ensure app user has a .cifrc
  template: src=cifrc.j2 dest="{{ app_user_home }}/.cifrc" owner={{ app_user }} group={{ app_user }} mode=0660

- name: Ensure .cifrc is linked to .profile
  lineinfile: dest="{{ app_user_home }}/.profile" line="source ~/.cifrc"

## TODO cif-tokens CIF_TOKEN / CIF_SMRT_TOKEN etc...
#- name: Add vars to app env
#  lineinfile: dest="{{ app_user_home }}/.profile" line="export RAILS_ENV={{ app_rails_env }}"